### ISSUE TITLE
Support for declaring events in markup

### ISSUE THREAD

**Issue by mwbrooks** [mwbrooks/thumbs.js#2]
Does thumbs.js support:

```
<a href="#" ontouchstart="fn();">Button</a>
```

**Comment by alunny** [comment]
something like this https://gist.github.com/639672

with a call to `evt.target.getAttribute` to find a string value and `eval` it instead (or maybe you need to use the function constructor to match the right context); off the top of my head

```
document.addEventListener('click', function (e) {
    var t = e.target;
    var a = t.getAttribute("ontouchstart");
    if (typeof a == "string") {
        var f = Function(a);
        f.call(t, e);
    }
}
```

**Comment by mwbrooks** [comment]
Commit c6a5d78c1752132ba95dd4442f97e922ca704b00
